// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2LA-th6kK_lvVRRL_q7Yxlz2iVT-uNIo',
    appId: '1:584920761858:web:46b5236f72f9efec1ec91b',
    messagingSenderId: '584920761858',
    projectId: 'mara-e6a5b',
    authDomain: 'mara-e6a5b.firebaseapp.com',
    databaseURL: 'https://mara-e6a5b-default-rtdb.firebaseio.com',
    storageBucket: 'mara-e6a5b.appspot.com',
    measurementId: 'G-EF8MS5216L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOQyLr9Ky177xRAQCJUSWTfAdixz7wYyA',
    appId: '1:584920761858:android:1b141f599f36e4a21ec91b',
    messagingSenderId: '584920761858',
    projectId: 'mara-e6a5b',
    databaseURL: 'https://mara-e6a5b-default-rtdb.firebaseio.com',
    storageBucket: 'mara-e6a5b.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcUsOb6MH9PPxFA1JxPJzWQ48u8g-j-Nc',
    appId: '1:584920761858:ios:6678a298cb1134841ec91b',
    messagingSenderId: '584920761858',
    projectId: 'mara-e6a5b',
    databaseURL: 'https://mara-e6a5b-default-rtdb.firebaseio.com',
    storageBucket: 'mara-e6a5b.appspot.com',
    iosBundleId: 'com.example.maraApp',
  );
}
