name: mara
description: testing flutter sdk

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
    assets:
      - assets/audio/piano.mp3

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.2.0
  flip_card: ^0.7.0
  video_player: ^2.3.5
  just_audio: ^0.9.24

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/image4.png