/// Flutter icons MiscIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MiscIcons
///      fonts:
///       - asset: fonts/MiscIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MiscIcons {
  MiscIcons._();

  static const _kFontFam = 'MiscIcons';
  static const String? _kFontPkg = null;

  static const IconData private = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData period = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chance = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData birth_control = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pregnant_woman = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audio = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contraception = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData safe_sex = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData important = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_mark = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pills_bottle = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quiz = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deadline = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData why = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disease_prevention = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_mark = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
